const canvas=document.querySelector('#invoice-canvas'),ctx=canvas.getContext('2d'),itemsRoot=document.querySelector('#items'),template=document.querySelector('#item-template'),logo=new Image();logo.src='Logo 1.png';
const fields={number:document.querySelector('#invoice-number'),date:document.querySelector('#invoice-date'),due:document.querySelector('#due-date'),customer:document.querySelector('#customer'),phone:document.querySelector('#phone'),email:document.querySelector('#email'),taxId:document.querySelector('#tax-id'),address:document.querySelector('#address'),discount:document.querySelector('#discount'),taxRate:document.querySelector('#tax-rate'),shipping:document.querySelector('#shipping'),payment:document.querySelector('#payment'),notes:document.querySelector('#notes')};
const today=new Date(),dueDate=new Date(today);dueDate.setDate(today.getDate()+7);const iso=date=>date.toISOString().slice(0,10);fields.date.value=iso(today);fields.due.value=iso(dueDate);fields.number.value=`B2B-INV-${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}${String(today.getDate()).padStart(2,'0')}`;
let itemId=0,rendering=false,rerender=false;
function money(value){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:2}).format(value||0)}
function numberValue(input){return Math.max(0,Number(input.value)||0)}
function addItem(values={}){const item=template.content.firstElementChild.cloneNode(true);item.dataset.id=++itemId;Object.entries(values).forEach(([key,value])=>{const input=item.querySelector(`[data-field="${key}"]`);if(input)input.value=value});item.querySelectorAll('input,textarea').forEach(input=>input.addEventListener('input',scheduleRender));item.querySelector('.remove-item').addEventListener('click',()=>{item.remove();renumber();scheduleRender()});itemsRoot.append(item);renumber();scheduleRender()}
function renumber(){[...itemsRoot.children].forEach((item,index)=>item.querySelector('.item-number').textContent=String(index+1).padStart(2,'0'))}
function getItems(){return[...itemsRoot.children].map(item=>{const qty=numberValue(item.querySelector('[data-field="qty"]')),rate=numberValue(item.querySelector('[data-field="rate"]')),amount=qty*rate,formatted=money(amount);item.querySelector('[data-field="amount"]').value=formatted;item.querySelector('.line-total').textContent=formatted;return{name:item.querySelector('[data-field="name"]').value.trim(),description:item.querySelector('[data-field="description"]').value.trim(),qty,rate,amount}})}
function calculate(){const items=getItems(),subtotal=items.reduce((sum,item)=>sum+item.amount,0),discount=Math.min(numberValue(fields.discount),subtotal),shipping=numberValue(fields.shipping),taxable=Math.max(0,subtotal-discount),tax=taxable*numberValue(fields.taxRate)/100,total=taxable+tax+shipping;document.querySelector('#subtotal').textContent=money(subtotal);document.querySelector('#tax-total').textContent=money(tax);document.querySelector('#grand-total').textContent=money(total);return{items,subtotal,discount,shipping,tax,total}}
function scheduleRender(){clearTimeout(scheduleRender.timer);scheduleRender.timer=setTimeout(renderInvoice,80)}
function text(value,x,y,size,weight=400,color='#151922',align='left'){ctx.font=`${weight} ${size}px Inter,Arial,sans-serif`;ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='top';ctx.fillText(String(value),x,y)}
function wrapped(value,x,y,maxWidth,lineHeight,maxLines=4,size=16,weight=400,color='#596273'){ctx.font=`${weight} ${size}px Inter,Arial,sans-serif`;ctx.fillStyle=color;ctx.textAlign='left';ctx.textBaseline='top';const words=String(value||'').split(/\s+/).filter(Boolean),lines=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width>maxWidth&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);lines.slice(0,maxLines).forEach((part,index)=>ctx.fillText(part+(index===maxLines-1&&lines.length>maxLines?'…':''),x,y+index*lineHeight));return Math.min(lines.length,maxLines)*lineHeight}
function rounded(x,y,width,height,radius,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,width,height,radius);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.stroke()}}
function line(x1,y1,x2,y2,color='#dfe3eb',width=1){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()}
function date(value){return value?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T00:00:00`)):'—'}
async function renderInvoice(){if(rendering){rerender=true;return}rendering=true;const totals=calculate(),rowHeight=118,pageHeight=Math.max(1754,790+totals.items.length*rowHeight+480);canvas.width=1240;canvas.height=pageHeight;ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#1e3a8a';ctx.fillRect(0,0,canvas.width,18);
  if(logo.complete&&logo.naturalWidth)ctx.drawImage(logo,70,58,410,137);text('INVOICE',1170,72,38,800,'#1e3a8a','right');text(fields.number.value||'INVOICE NUMBER',1170,122,17,700,'#596273','right');text('CREATE. CONNECT. GROW.',1170,160,11,700,'#1e3a8a','right');line(70,225,1170,225);
  text('BILL TO',70,268,12,800,'#1e3a8a');text(fields.customer.value||'Customer / Company',70,296,29,700);let customerY=340;if(fields.address.value)customerY+=wrapped(fields.address.value,70,customerY,600,23,3,16);const contacts=[fields.email.value,fields.phone.value,fields.taxId.value&&`GSTIN / Tax ID: ${fields.taxId.value}`].filter(Boolean).join('  ·  ');if(contacts)wrapped(contacts,70,customerY+5,620,22,2,14,500,'#687080');
  text('INVOICE DATE',835,270,11,800,'#687080');text(date(fields.date.value),835,294,17,600);text('DUE DATE',1030,270,11,800,'#687080');text(date(fields.due.value),1030,294,17,600);
  const tableY=440;rounded(70,tableY,1100,56,7,'#1e3a8a');text('#',98,tableY+19,12,800,'#fff');text('ITEM & DESCRIPTION',145,tableY+19,12,800,'#fff');text('QTY',805,tableY+19,12,800,'#fff','right');text('RATE',980,tableY+19,12,800,'#fff','right');text('AMOUNT',1140,tableY+19,12,800,'#fff','right');let y=tableY+56;
  totals.items.forEach((item,index)=>{ctx.fillStyle=index%2?'#fafbfc':'#fff';ctx.fillRect(70,y,1100,rowHeight);line(70,y+rowHeight,1170,y+rowHeight);text(index+1,98,y+26,15,600,'#596273');text(item.name||`Item ${index+1}`,145,y+23,18,700);if(item.description)wrapped(item.description,145,y+52,560,20,3,14);text(item.qty,805,y+27,16,600,'#151922','right');text(money(item.rate),980,y+27,16,600,'#151922','right');text(money(item.amount),1140,y+27,17,800,'#1e3a8a','right');y+=rowHeight});
  if(!totals.items.length){text('No bill items',620,y+35,16,500,'#7a8290','center');y+=90}const summaryY=y+42;text('PAYMENT / NOTES',70,summaryY,12,800,'#1e3a8a');if(fields.payment.value){text('Payment:',70,summaryY+31,14,700);wrapped(fields.payment.value,153,summaryY+31,490,21,2,14)}wrapped(fields.notes.value||'Thank you for your business.',70,summaryY+(fields.payment.value?83:31),600,23,5,15);
  const x=790;let ty=summaryY;text('Subtotal',x,ty,15,500,'#596273');text(money(totals.subtotal),1140,ty,16,700,'#151922','right');ty+=38;if(totals.discount){text('Discount',x,ty,14,500,'#596273');text(`− ${money(totals.discount)}`,1140,ty,15,600,'#b3312a','right');ty+=34}if(numberValue(fields.taxRate)){text(`Tax / GST (${numberValue(fields.taxRate)}%)`,x,ty,14,500,'#596273');text(money(totals.tax),1140,ty,15,600,'#151922','right');ty+=34}if(totals.shipping){text('Shipping',x,ty,14,500,'#596273');text(money(totals.shipping),1140,ty,15,600,'#151922','right');ty+=34}rounded(x,ty+13,350,92,8,'#1e3a8a');text('GRAND TOTAL',x+22,ty+38,12,800,'#b9c8f4');text(money(totals.total),1118,ty+33,25,800,'#fff','right');text('Amount in INR',1140,ty+116,11,500,'#7a8290','right');
  const footerY=canvas.height-150;ctx.fillStyle='#151922';ctx.fillRect(0,footerY,canvas.width,150);text('BEST2BUY.IN',70,footerY+35,22,800,'#fff');text('Creative media · Print · Digital · Web',70,footerY+70,13,500,'#9ca5b5');text('best2buyind@gmail.com',1170,footerY+35,16,600,'#fff','right');text('Coimbatore, Tamil Nadu, India',1170,footerY+68,13,500,'#9ca5b5','right');text('This is a computer-generated invoice.',620,footerY+112,10,500,'#747e8e','center');rendering=false;if(rerender){rerender=false;renderInvoice()}}
function printInvoice(){renderInvoice().then(()=>setTimeout(()=>window.print(),120))}
function downloadInvoice(){renderInvoice().then(()=>{const customer=(fields.customer.value||'customer').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase(),link=document.createElement('a');link.download=`${fields.number.value||'best2buy-invoice'}-${customer}.jpg`;link.href=canvas.toDataURL('image/jpeg',.95);link.click()})}
Object.values(fields).forEach(field=>field.addEventListener('input',scheduleRender));document.querySelector('#add-item').addEventListener('click',()=>addItem());document.querySelector('#print').addEventListener('click',printInvoice);document.querySelector('#print-mobile').addEventListener('click',printInvoice);document.querySelector('#download').addEventListener('click',downloadInvoice);document.querySelector('#download-mobile').addEventListener('click',downloadInvoice);document.querySelector('#reset-button').addEventListener('click',()=>{if(!confirm('Clear this invoice and start again?'))return;fields.customer.value='';fields.phone.value='';fields.email.value='';fields.taxId.value='';fields.address.value='';fields.discount.value='0';fields.taxRate.value='0';fields.shipping.value='0';fields.payment.value='';fields.notes.value='Thank you for your business. Please include the invoice number with your payment.';itemsRoot.innerHTML='';addItem()});logo.onload=renderInvoice;addItem({name:'Creative services',description:'Design and production services',qty:1,rate:0});
