const mainImage=document.querySelector('#main-image'),thumbs=[...document.querySelectorAll('.thumb')],quantity=document.querySelector('#quantity'),presets=[...document.querySelectorAll('[data-qty]')],selectionSummary=document.querySelector('#selection-summary'),shippingBadge=document.querySelector('#shipping-badge'),shippingCopy=document.querySelector('#shipping-copy'),form=document.querySelector('#order-form'),formStatus=document.querySelector('#form-status');
thumbs.forEach(thumb=>thumb.addEventListener('click',()=>{thumbs.forEach(item=>item.classList.remove('active'));thumb.classList.add('active');mainImage.style.opacity='.25';setTimeout(()=>{mainImage.src=thumb.dataset.image;mainImage.alt=thumb.dataset.alt;mainImage.style.opacity='1'},120)}));
presets.forEach(button=>button.addEventListener('click',()=>{quantity.value=button.dataset.qty;presets.forEach(item=>item.classList.toggle('active',item===button));updateSummary()}));
quantity.addEventListener('input',()=>{presets.forEach(button=>button.classList.toggle('active',button.dataset.qty===quantity.value));updateSummary()});
document.querySelectorAll('input[name="size"],input[name="delivery"]').forEach(input=>input.addEventListener('change',updateSummary));
function selected(name){return document.querySelector(`input[name="${name}"]:checked`)?.value||''}
function updateSummary(){const qty=Math.max(1,Math.round(Number(quantity.value)||1)),size=selected('size'),delivery=selected('delivery');selectionSummary.textContent=`${size} · ${qty} piece${qty===1?'':'s'}`;shippingBadge.classList.remove('charge');if(delivery.startsWith('Free local')){shippingBadge.textContent='FREE LOCAL DELIVERY';shippingCopy.textContent='Free delivery within a 10 km radius of Podanur, Coimbatore.'}else if(qty<=100){shippingBadge.textContent='FREE SHIPPING';shippingCopy.textContent='Shipping is free for quantities up to 100 pieces.'}else{shippingBadge.textContent='SHIPPING EXTRA';shippingBadge.classList.add('charge');shippingCopy.textContent='Shipping will be calculated after packing and paid by the customer at delivery or courier-office pickup.'}}
form.addEventListener('submit',event=>{event.preventDefault();const qty=Math.max(1,Math.round(Number(quantity.value)||0)),name=document.querySelector('#customer-name').value.trim(),area=document.querySelector('#customer-area').value.trim(),size=selected('size'),delivery=selected('delivery');if(!qty){formStatus.textContent='Please enter a valid quantity.';return}formStatus.textContent='';const shipping=delivery.startsWith('Free local')?'Free within 10 km of Podanur':qty<=100?'Free shipping for up to 100 pieces':'Shipping to be calculated and paid at delivery / collection';const message=[`Hello Best2Buy, I would like to order Flexible Fridge Magnet 1 mm.`,`Size: ${size}`,`Quantity: ${qty}`,`Delivery preference: ${delivery}`,`Shipping: ${shipping}`,name&&`Customer name: ${name}`,area&&`Delivery area / PIN: ${area}`,`Please confirm the price, artwork requirements and delivery details.`].filter(Boolean).join('\n');window.open(`https://wa.me/918778578974?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')});
updateSummary();
