const canvas=document.querySelector('#quote-canvas'),ctx=canvas.getContext('2d'),itemsRoot=document.querySelector('#items'),template=document.querySelector('#item-template'),logo=new Image();
logo.src='gmedia-logo.png';
const fields={customer:document.querySelector('#customer'),number:document.querySelector('#quote-number'),date:document.querySelector('#quote-date'),valid:document.querySelector('#valid-until'),subject:document.querySelector('#subject'),terms:document.querySelector('#terms')};
const today=new Date(),validDate=new Date(today);validDate.setDate(today.getDate()+15);const iso=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;fields.date.value=iso(today);fields.valid.value=iso(validDate);fields.number.value=`GMW-${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}${String(today.getDate()).padStart(2,'0')}`;
let itemId=0,renderTimer;
function money(value){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:2}).format(value||0)}
function addItem(values={}){const node=template.content.firstElementChild.cloneNode(true);node.dataset.id=++itemId;Object.entries(values).forEach(([key,value])=>{const input=node.querySelector(`[data-field="${key}"]`);if(input)input.value=value});node.querySelectorAll('input,textarea').forEach(input=>input.addEventListener('input',scheduleRender));node.querySelector('.remove-item').addEventListener('click',()=>{node.remove();renumber();scheduleRender()});itemsRoot.append(node);renumber();scheduleRender()}
function renumber(){[...itemsRoot.children].forEach((item,index)=>item.querySelector('.item-number').textContent=String(index+1).padStart(2,'0'))}
function getItems(){return[...itemsRoot.children].map(item=>{const qty=Math.max(0,Number(item.querySelector('[data-field="qty"]').value)||0),price=Math.max(0,Number(item.querySelector('[data-field="price"]').value)||0),total=qty*price;item.querySelector('[data-field="total"]').value=money(total);item.querySelector('.line-total').textContent=money(total);return{name:item.querySelector('[data-field="name"]').value.trim(),description:item.querySelector('[data-field="description"]').value.trim(),qty,price,total}})}
function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(renderQuote,80)}
function text(value,x,y,size,weight=400,color='#111',align='left'){ctx.font=`${weight} ${size}px Inter,Arial,sans-serif`;ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='top';ctx.fillText(value,x,y)}
function wrap(value,x,y,maxWidth,lineHeight,maxLines=4,size=18,weight=400,color='#596170'){ctx.font=`${weight} ${size}px Inter,Arial,sans-serif`;ctx.fillStyle=color;ctx.textAlign='left';ctx.textBaseline='top';const words=String(value||'').split(/\s+/).filter(Boolean),lines=[];let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);const shown=lines.slice(0,maxLines);shown.forEach((part,index)=>ctx.fillText(part+(index===maxLines-1&&lines.length>maxLines?'…':''),x,y+index*lineHeight));return shown.length*lineHeight}
function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function formatDate(value){return value?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T00:00:00`)):'—'}
function renderQuote(){const items=getItems(),rowHeight=145;canvas.width=1240;canvas.height=1754;ctx.fillStyle='#fff';ctx.fillRect(0,0,1240,1754);
  ctx.fillStyle='#ed176f';ctx.fillRect(0,0,1240,15);ctx.fillStyle='#f7a42d';ctx.fillRect(0,15,1240,7);
  if(logo.complete&&logo.naturalWidth)ctx.drawImage(logo,66,55,390,165);
  text('QUOTATION',1165,72,42,900,'#111','right');text(fields.number.value||'QUOTATION NUMBER',1165,128,17,700,'#7655d7','right');text('CREATIVE · DIGITAL · MEDIA',1165,162,11,800,'#ed176f','right');
  ctx.strokeStyle='#e0e2e6';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(70,236);ctx.lineTo(1170,236);ctx.stroke();
  text('QUOTATION FOR',70,276,12,800,'#ed176f');text(fields.customer.value||'Customer / Company',70,304,30,800);
  text('DATE',840,278,11,800,'#737986');text(formatDate(fields.date.value),840,303,17,600);text('VALID UNTIL',1030,278,11,800,'#737986');text(formatDate(fields.valid.value),1030,303,17,600);
  if(fields.subject.value){rounded(70,364,1100,86,10,'#faf6fb');text('PROJECT / SUBJECT',94,386,10,800,'#7655d7');wrap(fields.subject.value,94,410,1030,23,2,17,500,'#333740')}
  const tableY=fields.subject.value?490:390;rounded(70,tableY,1100,58,7,'#111');text('#',96,tableY+20,12,800,'#fff');text('PRODUCT / SERVICE & DESCRIPTION',142,tableY+20,12,800,'#fff');text('QTY',820,tableY+20,12,800,'#fff','right');text('RATE',980,tableY+20,12,800,'#fff','right');text('AMOUNT',1140,tableY+20,12,800,'#fff','right');
  let y=tableY+58;items.forEach((item,index)=>{ctx.fillStyle=index%2?'#fdfafd':'#fff';ctx.fillRect(70,y,1100,rowHeight);ctx.strokeStyle='#e2e4e8';ctx.beginPath();ctx.moveTo(70,y+rowHeight);ctx.lineTo(1170,y+rowHeight);ctx.stroke();text(String(index+1),96,y+25,15,600,'#697080');text(item.name||`Item ${index+1}`,142,y+22,20,750,'#111');wrap(item.description||'Description to be confirmed.',142,y+56,570,22,3,15,400,'#5e6674');text(String(item.qty),820,y+25,17,600,'#111','right');text(money(item.price),980,y+25,17,600,'#111','right');text(money(item.total),1140,y+25,18,800,'#b20d52','right');y+=rowHeight});
  const subtotal=items.reduce((sum,item)=>sum+item.total,0),summaryY=Math.min(y+38,1260);text('TERMS & CONDITIONS',70,summaryY,12,900,'#ed176f');wrap(fields.terms.value||'Terms and conditions to be confirmed.',70,summaryY+31,650,27,8,16,400,'#525966');
  text('Subtotal',790,summaryY,15,500,'#596170');text(money(subtotal),1140,summaryY,17,700,'#111','right');ctx.strokeStyle='#dedfe3';ctx.beginPath();ctx.moveTo(790,summaryY+42);ctx.lineTo(1140,summaryY+42);ctx.stroke();rounded(790,summaryY+62,350,100,9,'#111');text('GRAND TOTAL',816,summaryY+90,12,800,'#f4a6ca');text(money(subtotal),1115,summaryY+84,27,900,'#fff','right');text('Amount in INR',1140,summaryY+174,11,500,'#7a7f89','right');
  ctx.fillStyle='#111';ctx.fillRect(0,1586,1240,168);ctx.fillStyle='#ed176f';ctx.fillRect(0,1586,1240,7);text('GLORY MEDIA WORKS',70,1624,23,900,'#fff');text('Creative media · Digital marketing · Design',70,1660,13,500,'#bcb9c1');text('glorymediaworks@gmail.com',1170,1624,16,700,'#fff','right');text('+91 877 857 8974',1170,1658,15,600,'#f7a42d','right');text('Podanur, Coimbatore – 21',1170,1689,12,500,'#bcb9c1','right');text('Thank you for the opportunity to work with you.',620,1723,10,500,'#77727e','center')}
function downloadQuote(){renderQuote();const customer=(fields.customer.value||'customer').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase(),fileName=`${fields.number.value||'glory-media-quote'}-${customer}.jpg`,dataUrl=canvas.toDataURL('image/jpeg',.95),binary=atob(dataUrl.split(',')[1]),bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);const url=URL.createObjectURL(new Blob([bytes],{type:'image/jpeg'})),link=document.createElement('a');link.href=url;link.download=fileName;link.style.display='none';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),5000)}
function printQuote(){renderQuote();setTimeout(()=>window.print(),120)}
Object.values(fields).forEach(field=>field.addEventListener('input',scheduleRender));document.querySelector('#add-item').addEventListener('click',()=>addItem());document.querySelector('#download').addEventListener('click',printQuote);document.querySelector('#download-mobile').addEventListener('click',printQuote);document.querySelector('#reset').addEventListener('click',()=>{if(!confirm('Clear this quotation and start again?'))return;fields.customer.value='';fields.subject.value='';fields.terms.value='';itemsRoot.innerHTML='';addItem();scheduleRender()});logo.onload=renderQuote;addItem();
