const grid=document.querySelector('#product-grid'),search=document.querySelector('#product-search'),empty=document.querySelector('#empty-state');
const links=Array.isArray(window.BEST2BUY_PRODUCT_LINKS)?window.BEST2BUY_PRODUCT_LINKS:[];
let products=[];
function safe(value){return String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function meta(doc,key){return doc.querySelector(`meta[property="${key}"],meta[name="${key}"]`)?.content||''}
async function readProduct(link){const response=await fetch(link);if(!response.ok)throw new Error(`Could not read ${link}`);const doc=new DOMParser().parseFromString(await response.text(),'text/html');return{link,title:meta(doc,'og:title')||doc.title,description:meta(doc,'og:description')||meta(doc,'description'),image:meta(doc,'og:image'),category:meta(doc,'product:category')||'Best2Buy product',price:meta(doc,'product:price')||'Ask for price',badge:meta(doc,'product:badge')||'View product'}}
function render(query=''){const term=query.trim().toLowerCase(),visible=products.filter(item=>[item.title,item.category,item.description].join(' ').toLowerCase().includes(term));grid.innerHTML=visible.map(item=>`<article class="product-card"><a class="product-image" href="${safe(item.link)}"><img src="${safe(item.image)}" alt="${safe(item.title)}" loading="lazy"><span>${safe(item.badge)}</span></a><div class="product-copy"><small>${safe(item.category)}</small><h3><a href="${safe(item.link)}">${safe(item.title)}</a></h3><p>${safe(item.description)}</p><div><b>${safe(item.price)}</b><a href="${safe(item.link)}">View details <span>↗</span></a></div></div></article>`).join('');empty.hidden=visible.length>0}
async function load(){grid.innerHTML='<p class="loading">Loading products…</p>';const settled=await Promise.allSettled(links.map(readProduct));products=settled.filter(result=>result.status==='fulfilled').map(result=>result.value);render(search.value)}
search.addEventListener('input',()=>render(search.value));load();
